Bionic base image
concourse/bosh-io-stemcell-resource pull request #23
Opened 2019-02-21 17:31 UTC by chenbh

2019-02-22 16:53 UTC, zachgersh commented
@chenbh - are you going to drop the wip off of this?

Also, I assume you are going to go make changes to the concourse-ci pipeline to change the dockerfile location?

2019-02-22 19:28 UTC, chenbh commented
@zachgersh yep, the main pipeline change is at concourse/concourse#3364, I'll let you know once that's merged

I guess that instead of marking it as `wip`, it would've been better to leave a comment saying it's blocked until that PR is in

2019-02-26 13:52 UTC, cirocosta requested changes
Hey, It'd be nice to have the README reflecting the fact that now we have multiple images being built (with updated instructions for that).

It might also be the case that we don't need to have the tests being copied in the `test` stage and then run there - wdyt?

Thanks!

2019-02-26 13:52 UTC, cirocosta commented on dockerfiles/ubuntu/Dockerfile
> +FROM resource AS tests
Hey, Is there any reason why we'd need to run the tests twice given that at the `builder` phase we already run it? thxx!

2019-03-25 18:53 UTC, cirocosta approved these changes
SGTM

2019-03-26 13:48 UTC, merged